version: "3"

services:
  db:
    container_name: db
    image: postgres:latest
    env_file: .env
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
  redis:
    container_name: redis
    image: redis:latest
    env_file: .env
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data