version: "3"

services:
  db:
    container_name: db
    image: postgres:12
    env_file: .env
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
  redis:
    container_name: redis
    image: redis:latest
    env_file: .env
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data
  elasticsearch:
    image: elasticsearch:7.9.3
    env_file:
      - .env
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./.data/elasticsearch:/usr/share/elasticsearch/data