"""empty message

Revision ID: 05d01d066691
Revises: 164d855c97f0
Create Date: 2020-11-30 15:31:04.374696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d01d066691'
down_revision = '164d855c97f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_options_poll_id_fkey', 'user_options', type_='foreignkey')
    op.create_foreign_key('user_options_poll_id_fkey', 'user_options', 'user_polls', ['poll_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_options_poll_id_fkey', 'user_options', type_='foreignkey')
    op.create_foreign_key('user_options_poll_id_fkey', 'user_options', 'user_polls', ['poll_id'], ['id'])
    # ### end Alembic commands ###
