"""empty message

Revision ID: 0c2ba9850599
Revises: 29d9b1f0bc3b
Create Date: 2020-11-30 15:43:21.462015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2ba9850599'
down_revision = '29d9b1f0bc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_options_option_id_fkey', 'user_options', type_='foreignkey')
    op.create_foreign_key('user_options_option_id_fkey', 'user_options', 'options', ['option_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_options_option_id_fkey', 'user_options', type_='foreignkey')
    op.create_foreign_key('user_options_option_id_fkey', 'user_options', 'options', ['option_id'], ['id'])
    # ### end Alembic commands ###
