"""empty message

Revision ID: 164d855c97f0
Revises: e9c48fe09807
Create Date: 2020-11-01 17:23:10.649586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164d855c97f0'
down_revision = 'e9c48fe09807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('options_poll_id_fkey', 'options', type_='foreignkey')
    op.create_foreign_key('options_poll_id_fkey', 'options', 'polls', ['poll_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('polls_creator_id_fkey', 'polls', type_='foreignkey')
    op.create_foreign_key('polls_creator_id_fkey', 'polls', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('polls_creator_id_fkey', 'polls', type_='foreignkey')
    op.create_foreign_key('polls_creator_id_fkey', 'polls', 'users', ['creator_id'], ['id'])
    op.drop_constraint('options_poll_id_fkey', 'options', type_='foreignkey')
    op.create_foreign_key('options_poll_id_fkey', 'options', 'polls', ['poll_id'], ['id'])
    # ### end Alembic commands ###
