"""empty message

Revision ID: 29d9b1f0bc3b
Revises: 05d01d066691
Create Date: 2020-11-30 15:41:09.651197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d9b1f0bc3b'
down_revision = '05d01d066691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_polls_poll_id_fkey', 'user_polls', type_='foreignkey')
    op.create_foreign_key('user_polls_poll_id_fkey', 'user_polls', 'polls', ['poll_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_polls_poll_id_fkey', 'user_polls', type_='foreignkey')
    op.create_foreign_key('user_polls_poll_id_fkey', 'user_polls', 'polls', ['poll_id'], ['id'])
    # ### end Alembic commands ###
