"""empty message

Revision ID: 8285013310d1
Revises: 2ae311bdca23
Create Date: 2020-10-14 13:48:49.851423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8285013310d1'
down_revision = '2ae311bdca23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('polls_creator_fkey', 'polls', type_='foreignkey')
    op.create_foreign_key(None, 'polls', 'users', ['creator_id'], ['id'])
    op.drop_column('polls', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'polls', type_='foreignkey')
    op.create_foreign_key('polls_creator_fkey', 'polls', 'users', ['creator'], ['id'])
    op.drop_column('polls', 'creator_id')
    # ### end Alembic commands ###
